### ISSUE TITLE
unknown setting [cloud.aws.region]

### ISSUE THREAD

**Issue by mokio8** [synhershko/elasticsearch-cloud-deploy#26]
nodes won't start as long as cloud.aws.region is in elasticsearch.yml removing this entry solves this issue, however, the discovery service won't work outside of us-east-1. Was this a breaking change between 5.x and 6.x?

```
[2018-02-07T02:24:42,643][INFO ][o.e.p.PluginsService     ] [ip-10-0-9-209] loaded plugin [x-pack]
[2018-02-07T02:24:44,278][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: unknown setting [cloud.aws.region] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:312) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-6.1.3.jar:6.1.3]
```

**Comment by synhershko** [comment]
Interesting, I will have a look. Thanks for letting me know!

**Comment by jpveritone** [comment]
I just upgraded ES from 5.3.2 to 6.2.4 in AWS govcloud (region us-gov-west-1) and getting error...```
2018-06-29T17:30:27,058][INFO ][o.e.d.e.AwsEc2UnicastHostsProvider] [0.es-sync-mention-master.aws-us-gov-prod.veritone.com] Exception while retrieving instance list from AWS API: 
Unable to execute HTTP request: Connect to ec2.us-east-1.amazonaws.com:443 [ec2.us-east-1.amazonaws.com/54.239.29.8] failed: connect timed out``` Is there a resolution to this problem?

**Comment by jpveritone** [comment]
found a solution, for AWS gov-cloud updated elasticsearch.yml by adding `discovery.ec2.endpoint: ec2.us-gov-west-1.amazonaws.com`.
